TMEDIA-273 article header spacing
WPMedia/fusion-news-theme-blocks pull request #1005
Opened 2021-07-26 16:09 UTC by mattkim93

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
_Information about what you changed for this PR_

## Jira Ticket
- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-273)

## Acceptance Criteria
_copy from ticket_
- Article header, headline, subheadline, overline, byline, and date have the right spacing

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/headline-block,@wpmedia/article-body-block,@wpmedia/shared-styles,@wpmedia/subheadline-block,@wpmedia/byline-block`
3. open http://localhost/pf/kitchen-sink-article-without-lazy-loading/?_website=the-gazette and compare the article header spacing with https://app.zeplin.io/project/603fa53e2626ed1592e7c0e6/screen/6041330e984fd6a45ce1e088 and https://app.zeplin.io/project/603fa53e2626ed1592e7c0e6/screen/60491c21e5fbed0995b264b6

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]
![image](https://user-images.githubusercontent.com/45465140/127019038-ef2b1024-6315-4864-81a5-3b50cdb26971.png)

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]
![image](https://user-images.githubusercontent.com/45465140/127021979-93a1138c-196e-4ba7-907a-2a27bb2b32fd.png)
![image](https://user-images.githubusercontent.com/45465140/127022032-bbbf9727-39fe-4648-a185-0ff1eebec933.png)
![image](https://user-images.githubusercontent.com/45465140/127022074-2941c8ab-7ddb-4367-8d0b-206bf1db837a.png)
![image](https://user-images.githubusercontent.com/45465140/127022114-c10a2d92-7684-42b0-8909-2565706fe018.png)

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-07-27 11:17 UTC, matthewroach requested changes
There's quite a lot of spacing changes that are affecting areas other than the article output, as seen in Chromatic - can we confirm these are all intended changes as while these changes decrease the spacing in the article output - there are a lot of increased spacing changes to other blocks.

I recently came across some inconsistency with spacing in our codebase and it is something we do need to tackle - see my comment in - https://arcpublishing.atlassian.net/browse/TMEDIA-323

2021-07-27 11:17 UTC, matthewroach commented on blocks/right-rail-block/layouts/right-rail/default.scss
> +      padding: 0 map-get($spacers, 'md') 0 0;
What was the reason for altering the padding of the main section of the layout - looking at the chromatic run the gap between the main and right rail is now uneven

2021-08-03 20:49 UTC, nschubach commented
> There's quite a lot of spacing changes that are affecting areas other than the article output, as seen in Chromatic - can we confirm these are all intended changes as while these changes decrease the spacing in the article output - there are a lot of increased spacing changes to other blocks.
> 
> I recently came across some inconsistency with spacing in our codebase and it is something we do need to tackle - see my comment in - https://arcpublishing.atlassian.net/browse/TMEDIA-323

This is most certainly a side effect of your observations... the overline has the appropriate bottom margin applied now, but since the headline below it is using an inappropriate padding, and the overline not being a block (and thus, not collapse) will cause it to add space instead of the code's intended reduction of space.

Can confirm odd/un-intended spacing changes due to these changes. @RobinGiannattasio, thoughts?  Should this wait on a greater refactor from Matt's other story?

2021-08-05 19:23 UTC, matthewroach approved these changes, later dismissed

2021-08-05 21:44 UTC, matthewroach approved these changes

2021-08-09 15:36 UTC, merged