WIP: TMEDIA-346/medium_promo_refactor
WPMedia/fusion-news-theme-blocks pull request #1012
Opened 2021-07-28 14:58 UTC by farleyawapo

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
_Information about what you changed for this PR_

## Jira Ticket
- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-)

## Acceptance Criteria
_copy from ticket_

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l {blocks to link}`
3. {Next ....}

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-07-28 21:04 UTC, matthewroach requested changes
One small change

2021-07-28 21:04 UTC, matthewroach commented on blocks/medium-promo-block/features/medium-promo/default.jsx
> +  const { arcSite } = useFusionContext();
Add this to line 96 and pass through as we did for small promo

2021-08-03 15:51 UTC, nschubach requested changes
Just two minor removals.

2021-08-03 15:51 UTC, nschubach commented on blocks/shared-styles/_children/promos/medium/index.test.jsx
> +jest.mock('fusion:themes', () => (jest.fn(() => ({}))));
```suggestion
```
This doesn't seem to be used.

2021-08-03 15:51 UTC, nschubach commented on blocks/shared-styles/_children/promos/medium/index.test.jsx
> +    registerSuccessEvent: () => ({}),
```suggestion
```
Same here.  Not used.

2021-08-03 16:03 UTC, farleyawapo commented on blocks/shared-styles/_children/promos/medium/index.test.jsx
> +jest.mock('fusion:themes', () => (jest.fn(() => ({}))));
removed

2021-08-03 16:03 UTC, farleyawapo commented on blocks/shared-styles/_children/promos/medium/index.test.jsx
> +    registerSuccessEvent: () => ({}),
removed

2021-08-03 16:20 UTC, nschubach approved these changes

2021-08-04 18:15 UTC, matthewroach approved these changes
Nice work @farleyawapo 🎉

2021-08-04 19:16 UTC, merged