TMEDIA-400 subs POC
WPMedia/fusion-news-theme-blocks pull request #1028
Opened 2021-08-04 15:32 UTC by mattkim93

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
_Information about what you changed for this PR_
- Adds Identity blocks
- Adds dummy paywall feature in Subscriptions blocks

## Jira Ticket
- [TMEDIA-400](https://arcpublishing.atlassian.net/browse/TMEDIA-400)

## Acceptance Criteria
_copy from ticket_
https://paper.dropbox.com/doc/Themes-Subscriptions-Proof-of-Concept--BP187h99lPkbaZmi39hfPeYAAg-aHjkUr5TYxztGDAPBf4eb

## Test Steps
- Add test steps a reviewer must complete to test this PR

See above paper doc for test steps

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- See above paper doc

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-08-04 20:09 UTC, mattkim93 commented on blocks/identity-block/components/Identity.jsx
> +      if (!window.realFetch) {
For local dev only

2021-08-05 12:50 UTC, matthewroach commented on blocks/subscriptions-block/features/paywall/default.jsx
> +  useEffect(() => {
The `useEffect`s in here are for demo purpose. Paywall is another concept item we is too be looked at

2021-08-05 18:25 UTC, JackHowa reviewed
Have a couple of questions. Is there a good way of getting this up and running for me? I'm curious about local dev instructions

2021-08-05 18:25 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
> +  const rightNavSection = useMemo(() => <NavSection side="right" />, []);
not sure I follow what's happening here. why is `useMemo` necessary here?

2021-08-05 18:25 UTC, JackHowa commented on blocks/identity-block/features/facebook-login/default.jsx
> +import useIdentity from '../../components/Identity.jsx';
think the `.jsx` can be removed here 

```suggestion
import useIdentity from '../../components/Identity';
```

2021-08-05 18:25 UTC, JackHowa commented on blocks/identity-block/features/facebook-login/default.jsx
> +              data-width="512"
is there documentation for some of these fields? I don't know the fb api

2021-08-05 18:25 UTC, JackHowa commented on blocks/identity-block/features/forgot-password/request.jsx
> +            {error.message && error.message.length < 100 && <p>{error.message}</p>}
shorter than 100 char error message? is there something we need to worry about for showing this to customers?

2021-08-05 18:25 UTC, JackHowa commented on blocks/identity-block/features/header-account-action/default.jsx
> +    // cancel subscription to useEffect
nice

2021-08-06 15:27 UTC, JackHowa requested changes
Not really able to replicate the demo based on the dropbox doc. I don't see any login or functionality in the headers. 

I've imported the pages and the templates. I'm on the zscaler vpn. Let me know if you're available to pair @mattkim93

2021-08-10 19:33 UTC, mattkim93 commented on blocks/identity-block/components/Identity.jsx
> +  if (!isInit && arcSite && subscriptions?.identity?.apiOrigin) {
from here to line 35 should be taken out

2021-08-24 20:38 UTC, JackHowa commented
accepted as done

2021-08-24 20:38 UTC, closed without merging