TMEDIA-430 nav section re-render
WPMedia/fusion-news-theme-blocks pull request #1041
Opened 2021-08-12 21:37 UTC by JackHowa

investigation: 

- Matthew found re-rendering of the NavSection disrupting identity block progress
- He patched with useMemo around navsection 
- The reason they are re-rendering is due to the hooks changing and the subsequent "new" children props 
- I tried: 
-- to remove passing those children in as props via that spread props
-- refactoring the component to render the children in a different way 
-- memoizing the components of various other levels of the dom 

to test: 

in the identity block: 

```
import { useState } from 'react';
import Identity from '@arc-publishing/sdk-identity';
import { useFusionContext } from 'fusion:context';
import getProperties from 'fusion:properties';
import { isServerSide } from '@wpmedia/engine-theme-sdk';

// const useIdentity = () => ({
//   Identity,
//   isInitialized: true,
// });

// keep skelton for future use
const useIdentity = () => {
  console.log('running hook');
  const { arcSite } = useFusionContext();
  const { subscriptions } = getProperties(arcSite);
  const [
    isInit,
    setIsInit,
  ] = useState(() => !!Identity.apiOrigin);

  // todo: add subscriptions logic
  return ({
    Identity,
    isInitialized: true,
  });
};
export default useIdentity;

```

- As in the poc, include the identity block within the header nav chain and the right or left side 
- Run the profiler and make sure headernav login does not re-render 

## Description
_Information about what you changed for this PR_

## Jira Ticket
- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-)

## Acceptance Criteria
_copy from ticket_

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l {blocks to link}`
3. {Next ....}

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-08-12 21:43 UTC, JackHowa commented
interesting need to ensure the interactivity still works as expected (looking at tests)

2021-08-12 21:45 UTC, JackHowa commented
interesting, will also have to look at screenshot specificity. this looks like a false alarm chromatic

<img width="1410" alt="Screen Shot 2021-08-12 at 16 44 36" src="https://user-images.githubusercontent.com/5950956/129274167-1d0bde49-fb47-4cf5-b83c-9040e827819d.png">

2021-08-12 22:06 UTC, JackHowa commented
made some changes to move the styled components to clean it up a bit

2021-08-16 20:26 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.jsx
> +  const onScrollEvent = (evt) => {
this was copy-pasted from the default component here

2021-08-16 20:26 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.jsx
> +    <div className={`nav-logo nav-logo-${alignment} ${isLogoVisible ? 'nav-logo-show' : 'nav-logo-hidden'} ${isLogoSVG ? 'svg-logo' : ''}`}>
variable renamed for clarity

2021-08-16 20:26 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-logo.test.jsx
> -    expect(navLogo.hasClass('nav-logo-show')).toBe(true);
test logic removed as component now handles showing logo by itself

2021-08-16 20:28 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
> -              {...props}
using children props explicitly here so that it's more apparent how this is working

2021-08-16 20:36 UTC, nschubach approved these changes, later dismissed
Checks out here.  I would request @matthewroach or @farleyawapo take a look as well.

2021-08-17 12:55 UTC, matthewroach commented
I am still seeing re-renders of children components when you scroll and the navigation bar height changes

https://user-images.githubusercontent.com/868127/129729332-4fd4d896-865f-428f-93d3-9390fa1bd617.mp4

2021-08-17 12:56 UTC, matthewroach requested changes
Still seeing re-renders of children components

2021-08-17 15:58 UTC, JackHowa commented
cool thanks for showing this @matthewroach 

think I have the fix. gotta clean it up 

![Screen Shot 2021-08-17 at 10 56 37](https://user-images.githubusercontent.com/5950956/129760113-19aad602-0270-4216-9c8b-9b0899ab1232.png)

2021-08-17 17:43 UTC, JackHowa commented
updated @matthewroach . No longer re-rendering headernavaction child on scroll 

![Screen Shot 2021-08-17 at 11 02 23](https://user-images.githubusercontent.com/5950956/129775023-a2f7875a-84d1-4330-9861-f912f0a0f455.png)

2021-08-17 17:48 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/_children/nav-section.jsx
> +                {children}
importantly, we're passing in props this way rather than relying upon children as a global variable

2021-08-17 17:50 UTC, JackHowa commented on blocks/header-nav-chain-block/chains/header-nav-chain-block/default.jsx
> +          {children}
passing in children

2021-08-17 19:51 UTC, matthewroach reviewed
Pulling out components from the parent component into smaller children files - should we also pull out the tests to allow a 1:1 mapping for files and tests to keep things consistent and clearer?

2021-08-17 21:10 UTC, JackHowa commented
> Pulling out components from the parent component into smaller children files - should we also pull out the tests to allow a 1:1 mapping for files and tests to keep things consistent and clearer?

Moved some of the tests that I could extract. I couldn't find an analog to widgetlist. Let me know if you have other feedback @matthewroach

2021-08-18 10:22 UTC, matthewroach approved these changes
Thanks @JackHowa - All looks good 👍

2021-08-18 15:40 UTC, merged