TMEDIA-457: Fixup Paywall Block and clean up usePaywall Hook
WPMedia/fusion-news-theme-blocks pull request #1144
Opened 2021-10-25 15:42 UTC by nschubach

## Description
Finalize the paywall block component.  Fix bug with layer/video.  Reduce footprint of usePaywall to only necessary functionality, simplifying logic.

## Jira Ticket
- [TMEDIA-457](https://arcpublishing.atlassian.net/browse/TMEDIA-457)

## Acceptance Criteria
See Ticket.

## Test Steps
1. Checkout this branch `git checkout tmedia-457-paywall-block`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/subscriptions-block`
3. Ensure that You have the following two article pages.  If not, re-import pbdata:
![image](https://user-images.githubusercontent.com/2287238/138727536-ec22396b-1bcf-40fb-b21d-99bc7baebebd.png)
    * pb data: https://corecomponents.arcpublishing.com/pb-data/mongo/corecomponents-local.tar.gz
4. Check that you have the Paywall Block added and configured (this could potentially be placed inside a shared Fragment like http://localhost/pagebuilder/editor/curate?p=pNFbp320KN4TQr&v=vIMZut10KN4TQr )
![image](https://user-images.githubusercontent.com/2287238/139155388-a011ae65-bc43-41b2-982f-aa365acba51f.png)

![image](https://user-images.githubusercontent.com/2287238/139155159-2e9d5493-5d3e-449b-992c-73e47762cb14.png)
5. Log in using: http://localhost/pf/account/login/?_website=the-gazette
6. Open the original Kitchen Sink Article:
    * http://localhost/pf/kitchen-sink-article-jc/?_website=the-gazette
7. Open Brent's copy:
    * http://localhost/pf/ksa/?_website=the-gazette
8. The Paywall should appear.
9. Log out.
10. Clear cookies and localStorage for localhost.
    * 
![image](https://user-images.githubusercontent.com/2287238/139154880-a89bd294-6d9c-4245-a66f-c263ea989b07.png)
    * 
![image](https://user-images.githubusercontent.com/2287238/139154928-4ab2bc43-f6cb-4b6a-95ed-5cdc05b73ca4.png)
11. Open the original Kitchen Sink Article:
    * http://localhost/pf/kitchen-sink-article-jc/?_website=the-gazette
12. Open Brent's copy:
    * http://localhost/pf/ksa/?_website=the-gazette
13. The register wall should appear

## Effect Of Changes
### Before
No paywall would appear for going over the allocated views.

### After
A Regwall appears when going over the view count (currently 1)
![image](https://user-images.githubusercontent.com/2287238/139155524-da4545b2-2c5e-44e4-9146-ac400348c46e.png)

A Paywall appears when going over the view count (currently 2)
![image](https://user-images.githubusercontent.com/2287238/139155815-6bb3b64c-22aa-4996-b0e1-2bfd84e2ebab.png)

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-10-28 10:06 UTC, matthewroach requested changes
@nschubach I am seeing the following issues

1. Memory leak warning in the console

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at PaywallOffer (webpack-internal:///./bundle/linked_modules/@wpmedia/subscriptions-block/components/PaywallOffer/index.jsx:40:25)
```

2. The "Registration Wall" does not show on subsequent page views
    * Using the-gazette which is set to have reg wall shown **after 1** view, then the paywall **after 3** views. 
    * I view article 1, then go to article 2
         * I see the Registration Wall appear as expected
    * I go back to the homepage and click to see a third article
         * Expectation is that I would see the Registration wall as I've exceeded the 1 article limit as before
         * Actual Result is I am presented with the Paywall - Note: I've not logged in yet - which means I should still only ever see the registration wall

3. The Preview mode in Admin - "Show Payment Wall" is not working as expected - When I choose the option in the Admin from the drop down no paywall is shown

Other - 
Now we are not using language translations were these removed from Lokalise?

2021-10-28 10:06 UTC, matthewroach commented on blocks/subscriptions-block/features/paywall/default.jsx
> +      defaultValue: 'hide',
`defaultValue` should be `bottomHalf` this is producing errors in the console

```Warning: Failed prop type: Invalid prop `customFields.displayMode` of value `hide` supplied to `Paywall`, expected one of ["bottomHalf","full","modal"].```

2021-10-28 10:06 UTC, matthewroach commented on blocks/subscriptions-block/features/paywall/default.jsx
>        defaultValue: '/account/login',
Can we add a trailing slash to the URL

2021-10-28 10:06 UTC, matthewroach commented on blocks/subscriptions-block/features/paywall/default.jsx
> +      defaultValue: 'Subscribe to continue reading.',
This should be "Register to continue reading."

2021-10-28 10:06 UTC, matthewroach commented on blocks/subscriptions-block/components/RegwallOffer/index.jsx
> +        actionUrl={`${actionUrl}?_cid=${campaignCode}`}
`_cid` should not be used here - The sign up form does not use this param

2021-10-28 10:06 UTC, matthewroach commented on blocks/subscriptions-block/components/PaywallOffer/index.jsx
> +          : `${actionUrl}?_cid=${campaign}`}
What is the `_cid` param? and why are we using underscores? No other query params we have implemented is using this pattern

2021-10-28 14:14 UTC, nschubach commented
> @nschubach I am seeing the following issues
> 
> 1. Memory leak warning in the console
> 
> ```
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>     at PaywallOffer (webpack-internal:///./bundle/linked_modules/@wpmedia/subscriptions-block/components/PaywallOffer/index.jsx:40:25)
> ```
> 
> 1. The "Registration Wall" does not show on subsequent page views
>    
>    * Using the-gazette which is set to have reg wall shown **after 1** view, then the paywall **after 3** views.
>    * I view article 1, then go to article 2
>      
>      * I see the Registration Wall appear as expected
>    * I go back to the homepage and click to see a third article
>      
>      * Expectation is that I would see the Registration wall as I've exceeded the 1 article limit as before
>      * Actual Result is I am presented with the Paywall - Note: I've not logged in yet - which means I should still only ever see the registration wall
> 2. The Preview mode in Admin - "Show Payment Wall" is not working as expected - When I choose the option in the Admin from the drop down no paywall is shown
> 
> Other - Now we are not using language translations were these removed from Lokalise?
1.  Looking into the memory warning.

2. The rules are setup very tight for the demo (1 free story to register, 2 to subscribe) and @jecerovac2 verified that this is the way the rules should work.  The Subscriptions API will count every read on refresh so it doesn't matter if you register or not, it will keep counting until you hit the subscribe limit.

3.  Looking into this.

Other - I did not add anything to Lokalise, is it added automatically?  I'll have to figure out how to log in and look I guess.  (I've never logged into it.)

2021-10-28 14:16 UTC, nschubach commented on blocks/subscriptions-block/features/paywall/default.jsx
> +      defaultValue: 'hide',
Yup, copy paste error. :/

2021-10-28 14:16 UTC, nschubach commented on blocks/subscriptions-block/features/paywall/default.jsx
>        defaultValue: '/account/login',
Done

2021-10-28 14:16 UTC, nschubach commented on blocks/subscriptions-block/features/paywall/default.jsx
> +      defaultValue: 'Subscribe to continue reading.',
Done

2021-10-28 14:18 UTC, nschubach commented on blocks/subscriptions-block/components/RegwallOffer/index.jsx
> +        actionUrl={`${actionUrl}?_cid=${campaignCode}`}
I went back and forth on this.  The campaign code COULD be sent with a registration rule so I put it in there in case it was going to be used, but I'll take it out.

2021-10-28 14:37 UTC, nschubach commented on blocks/subscriptions-block/components/PaywallOffer/index.jsx
> +          : `${actionUrl}?_cid=${campaign}`}
This is left over from @visionbegin 's story.  I don't know where it came from.

2021-10-29 14:31 UTC, nschubach commented
Rules have been updated to prevent showing the subwall unless registered.  My previous knowledge on the state of localStorage when you log in from anonymous has been changed.

2021-11-01 10:21 UTC, matthewroach requested changes

2021-11-01 10:21 UTC, matthewroach commented on blocks/subscriptions-block/components/PaywallOffer/index.jsx
> +          : `${actionUrl}?_cid=${campaign}`}
This needs updated to be `campaign` if we need to use it. If the value is always `default` then the `/offer/` page will default to getting the default offer

2021-11-01 16:50 UTC, nschubach commented on blocks/subscriptions-block/components/PaywallOffer/index.jsx
> +          : `${actionUrl}?_cid=${campaign}`}
This now uses `campaign` as the url parameter and has some logic to not include it if it's `default`.

2021-11-02 13:14 UTC, matthewroach approved these changes
All looks good now @nschubach

2021-11-02 14:33 UTC, merged