IN PROGRESS Tmedia 628 lead art default eager
WPMedia/fusion-news-theme-blocks pull request #1237
Opened 2022-01-25 19:45 UTC by JackHowa

## Description
Set image loading on the lead art image type to be eager by default 

## Jira Ticket
- [TMEDIA-628](https://arcpublishing.atlassian.net/browse/TMEDIA-628)

## Acceptance Criteria
- Show eager by default for image type lead art 
- New custom field called Image Loading Strategy for Lead Art block, set to ‘eager’ by default with ‘lazy’ as the other option

## Test Steps

1. Checkout this branch `git checkout TMEDIA-628-lead-art-default-eager`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/lead-art-block`
3. Go to 

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2022-01-25 20:04 UTC, JackHowa commented on blocks/lead-art-block/features/leadart/default.jsx
> +      /* istanbul ignore next */
ignored these lines as testing them is going to require looking at implementation details of installed packages

2022-01-25 20:04 UTC, JackHowa commented on blocks/lead-art-block/features/leadart/default.jsx
> +            pageCountPhrase={/* istanbul ignore next */ (current, total) => this.phrases.t('global.gallery-page-count-text', { current, total })}
ignored as this is testing the usage of another library and the translations count here

2022-01-26 12:21 UTC, matthewroach requested changes
In PageBuilder Editor the drop down gives the user three options
1. ---
2. Eager
3. Lazy

Selecting either 2 or 3 works as expected the `img` get the correct value added to the `loading` attribute - if a user selection option 1 then no `loading` attribute is given - based on the comment in the code and the `defaultValue` it should always be getting the `eager` value. PageBuilder sets the `imageLoadingStrategy` prop to an empty string when using option 1. The block will need to account for this and ensure if it's an empty string the default is used as intended

One other small item - All the custom fields for the lear art block are categorized - should we put this new option under an "Image" category?

<img width="272" alt="Microsoft Edge-2022-01-26-12-13 23" src="https://user-images.githubusercontent.com/868127/151161127-1c304f0a-13c9-4cd3-9d63-dd8004769f3c.png">

2022-01-26 12:21 UTC, matthewroach commented on blocks/lead-art-block/features/leadart/default.jsx
> +    // todo: refactor dynamic loading of another block
Do we have a ticket for this? Not sure I fully understand the intent of the todo

2022-01-26 15:07 UTC, JackHowa commented
> In PageBuilder Editor the drop down gives the user three options
> 
> 1. 
> 2. Eager
> 3. Lazy
> 
> Selecting either 2 or 3 works as expected the `img` get the correct value added to the `loading` attribute - if a user selection option 1 then no `loading` attribute is given - based on the comment in the code and the `defaultValue` it should always be getting the `eager` value. PageBuilder sets the `imageLoadingStrategy` prop to an empty string when using option 1. The block will need to account for this and ensure if it's an empty string the default is used as intended
> 
> One other small item - All the custom fields for the lear art block are categorized - should we put this new option under an "Image" category?
> 
> <img alt="Microsoft Edge-2022-01-26-12-13 23" width="272" src="https://user-images.githubusercontent.com/868127/151161127-1c304f0a-13c9-4cd3-9d63-dd8004769f3c.png">

Not sure I follow what you're suggesting. I can check for an empty string in the props? 

I'm basing this off of the documentation: 

```
    imageLoadingStrategy: PropTypes.oneOf([
      'lazy', 'eager',
    ]).tag(
      {
        label: 'Image Loading Strategy',
        defaultValue: 'eager',
        labels: {
          eager: 'Eager',
          lazy: 'Lazy',
        },
      },
    ),
```

```
    mySelectField: PropTypes.oneOf([
      'foo', 'bar', 'baz'
    ]).tag({
      defaultValue: 'bar',
      description: 'This custom field is useless',
      group: 'examples',
      labels: { foo: 'Foo', bar: 'Bar', baz: 'Baz' }
    })
```
https://redirector.arcpublishing.com/alc/arc-products/pagebuilder/fusion/developer-documentation/custom-fields/

2022-01-26 15:11 UTC, matthewroach commented
@JackHowa - this is part of how PageBuilder Editor treats the `oneOf` type - the option `---` is passed to the component as an empty string, and if the requirement is to always have either `eager` or `lazy` present on the image we have to account for an empty string and ensure its caught via code

2022-01-26 15:17 UTC, JackHowa commented
> @JackHowa - this is part of how PageBuilder Editor treats the `oneOf` type - the option `---` is passed to the component as an empty string, and if the requirement is to always have either `eager` or `lazy` present on the image we have to account for an empty string and ensure its caught via code

Huh interesting. I wonder if there's a bug ticket for this behavior

2022-01-26 15:19 UTC, JackHowa commented on blocks/lead-art-block/features/leadart/default.jsx
> +    // todo: refactor dynamic loading of another block
I can remove clients wanting to use their own ads block here. but it may have just been an idea; I can remove the todo

2022-01-26 15:23 UTC, JackHowa commented
> One other small item - All the custom fields for the lear art block are categorized - should we put this new option under an "Image" category?

Updated after asking Jenae which category to go into

2022-01-26 15:43 UTC, matthewroach approved these changes

2022-01-26 15:43 UTC, merged