TMEDIA-586 - Remove export for blocks
WPMedia/fusion-news-theme-blocks pull request #1266
Opened 2022-02-09 14:22 UTC by matthewroach

## Description

Blocks were never designed to be consumed via code only via PageBuilder, some blocks have exported code to be made available to other blocks, and this is an anti-pattern and not a supported way of using blocks.

## Jira Ticket
- [TMEDIA-586](https://arcpublishing.atlassian.net/browse/TMEDIA-586)

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout TMEDIA-586`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/ads-block,@wpmedia/byline-block,@wpmedia/date-block,@wpmedia/links-bar-block,@wpmedia/numbered-list-block,@wpmedia/overline-block,@wpmedia/placeholder-image-block,@wpmedia/results-list-block,@wpmedia/video-player-block`
3. Valid nothing is broken and current pages/templates are still working as expected

## Dependencies or Side Effects
Custom blocks could be relying on these imports which would cause issues in their code, the import would stop working. These imports have not been supported, and client would need to adjust their code to account for these changes

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2022-02-09 15:06 UTC, JackHowa commented on blocks/placeholder-image-block/index.js
> +
you're keeping this one?

2022-02-09 15:08 UTC, JackHowa commented on blocks/placeholder-image-block/index.js
> +
Looks like there may have been a reason for this? 

```
Two “blocks” that are on watch include: 

Global Phrases block [arc-themes-blocks/blocks/global-phrases-block at canary · WPMedia/arc-themes-blocks](https://github.com/WPMedia/fusion-news-theme-blocks/tree/canary/blocks/global-phrases-block) 

Placeholder block [arc-themes-blocks/blocks/placeholder-image-block at canary · WPMedia/arc-themes-blocks](https://github.com/WPMedia/fusion-news-theme-blocks/tree/canary/blocks/placeholder-image-block)
```

2022-02-09 15:15 UTC, matthewroach commented on blocks/placeholder-image-block/index.js
> +
Yeah - if you look at the ticket it's documented why these need to be kept

2022-02-09 15:17 UTC, JackHowa commented on blocks/placeholder-image-block/index.js
> +
ah didn't see it deep in the comments

2022-02-09 15:33 UTC, JackHowa requested changes, later dismissed
Seeing some errors around ads-block. if you go to a gallery that has ads in it, then scroll to the ad, you will see the error http://localhost/pf/all-blocks/?_website=the-sun

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `AdBlock`.
```

2022-02-09 15:46 UTC, JackHowa reviewed
ads working as expected -- sorry for the hassle on this one 
![Screen Shot 2022-02-09 at 09 45 52](https://user-images.githubusercontent.com/5950956/153236722-87fd9238-1539-477a-9744-8d46b62ee688.png)

2022-02-09 15:46 UTC, JackHowa approved these changes
oops approved

2022-02-10 15:41 UTC, matthewroach commented
Awaiting feedback from product before we merge this - it may get held up based on approach we want to take with giving clients a heads up on the changes coming

2022-02-11 17:00 UTC, JackHowa commented
do not merge this -- awaiting product go-ahead

2022-02-11 17:01 UTC, RobinGiannattasio commented
NERD ALERT NERD ALERT!

I love using PR labels :D

2022-02-11 17:02 UTC, JackHowa commented
hahah at risk of spamming Matthew, yeah I just like the harsh red color of 'Do not merge' as well -- feel like it matches the intent

2022-02-11 17:05 UTC, RobinGiannattasio commented
Haha, well, even thought we are spamming Matthew - one real comment!

We should make sure to be cognizant of changing the base branch when we *are* ready to merge, since there will be a new release that this is associated with.

2022-04-04 17:45 UTC, merged