wip TMEDIA 858 header block
WPMedia/fusion-news-theme-blocks pull request #1344
Opened 2022-05-13 17:35 UTC by JackHowa

@malavikakoppula todo: 
- Add large, medium, and small sizes to the blocks storybook

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description

_Information about what you changed for this PR_

## Jira Ticket

- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-)

## Acceptance Criteria

_copy from ticket_

## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l {blocks to link}`
3. {Next ....}

## Effect Of Changes

### Before

_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After

_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects

_Examples of dependencies or side effects are:_

- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2022-05-16 13:59 UTC, nschubach commented on blocks/header-block/package.json
> +}
```suggestion
}

```

2022-05-16 14:07 UTC, nschubach requested changes, later dismissed
Just a few small changes I see.

2022-05-16 14:07 UTC, nschubach commented on blocks/header-block/features/header/default.test.jsx
> +});
```suggestion
describe("when no custom fields provided", () => {
	it("should fallback to an empty object and render defaults", () => {
		const wrapper = mount(<Header />);
		expect(wrapper.text()).toEqual("");
		const mediumHeader = wrapper.find(".b-header--medium");
		expect(mediumHeader).toExist();
	});
});
```

2022-05-16 14:08 UTC, nschubach commented on blocks/header-block/package.json
> +}
This is just adding a newline at the EOF

2022-05-16 14:09 UTC, nschubach commented on blocks/header-block/features/header/default.test.jsx
> +});
Should have the "it" in a "describe"

2022-05-16 14:29 UTC, nschubach commented on .storybook/themes/news.scss
> +@use "../../blocks/header-block";
Can we alphabetize this?  The list is probably going to get long and finding things would be easier.

2022-05-16 19:14 UTC, JackHowa commented on blocks/header-block/features/header/default.test.jsx
> +});
updated

2022-05-16 19:15 UTC, JackHowa commented on .storybook/themes/news.scss
> +@use "../../blocks/header-block";
updated

2022-05-17 17:48 UTC, nschubach approved these changes

2022-05-17 19:10 UTC, merged