Tmedia 724 header nav responsive feedback
WPMedia/fusion-news-theme-blocks pull request #1403
Opened 2022-07-05 08:55 UTC by JackHowa

- Fixes stylelint issue
- Fixes bad ternary logic warning with code quality
- Updates for the upcoming merge

2022-07-05 08:56 UTC, JackHowa commented
merging in upstream data is too messy; will cherry-pick updates

2022-07-05 11:07 UTC, JackHowa commented on blocks/header-nav-chain-block/_index.scss
> +	&--not-scrolled {
updated

2022-07-06 21:07 UTC, visionbegin requested changes
@JackHowa Appreciate the work, but a simple isScrolled var does not correctly implement the behavior of minimizing the height of the nav from its starting height once the user starts scrolling.

2022-07-07 14:42 UTC, JackHowa commented
> Appreciate the work, but a simple isScrolled var does not correctly implement the behavior of minimizing the height of the nav from its starting height once the user starts scrolling.

I'm not sure what you mean. It will apply the style of whatever is set to "header-nav-chain-scrolled". There's an event listener for on scroll behavior. Based on previous discussions and work, we want to have the customer set the height and, by extension, offset in the theme file, right? Setting in-line styles is currently overriding what's in the theme file that @matthewroach added. 

@visionbegin

2022-07-11 13:13 UTC, JackHowa commented
used as reference in #1386

2022-07-11 13:13 UTC, closed without merging