TMEDIA 725: Convert Footer block
WPMedia/fusion-news-theme-blocks pull request #1496
Opened 2022-08-30 22:25 UTC by nschubach

## Description

Convert Footer block to V2

## Jira Ticket

- [TMEDIA-725](https://arcpublishing.atlassian.net/browse/TMEDIA-725)

## Acceptance Criteria

Footer block is migrated to the new architecture
* Includes Custom fields of:
  * ‘Lazy Load block?’ checkbox - defaulted to false (with existing help text)\

## Test Steps

1. Checkout this branch `git checkout tmedia-725`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/footer-block`
3. Open `https://localhost/pagebuilder/pages`
4. Add Footer block to a test page

## Effect Of Changes

### Before

### After

## Dependencies or Side Effects

N/A

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2022-08-31 20:58 UTC, nschubach commented on blocks/footer-block/features/footer/default.jsx
>  		locale = "en",
```suggestion
		locale,
```

2022-09-02 12:51 UTC, matthewroach requested changes

2022-09-02 12:51 UTC, matthewroach commented on blocks/footer-block/_index.scss
> +		a:not(:last-child) {
This isn't used anywhere - is it still needed?

2022-09-02 12:51 UTC, matthewroach commented on .storybook/themes/news.scss
> +					components: (
These appear to be duplicates of the values set on `footer-social-links`

2022-09-02 15:18 UTC, nschubach commented on blocks/footer-block/_index.scss
> +		a:not(:last-child) {
oh yeah.  I don't need that anymore.  Removing.

2022-09-02 15:21 UTC, nschubach commented on .storybook/themes/news.scss
> +					components: (
Yep, I moved it and must have forgot to delete them.

2022-09-02 15:58 UTC, matthewroach approved these changes, later dismissed

2022-09-02 16:40 UTC, ecarlisle requested changes

2022-09-02 16:40 UTC, ecarlisle commented on blocks/footer-block/README.md
> +- twitter-link
We usually pair these in a markdown table with"default (English)" examples.

2022-09-02 16:40 UTC, ecarlisle commented on blocks/footer-block/README.md
> +- twitter-link
We usually pair these in a markdown table with"default (English)" examples.

2022-09-02 16:40 UTC, ecarlisle commented on blocks/footer-block/README.md
>  ## Additional Considerations
```suggestion
```

2022-09-02 16:40 UTC, ecarlisle commented on blocks/footer-block/README.md
>  ## Additional Considerations
We can probably take this out entirely.

2022-09-02 16:45 UTC, ecarlisle commented on blocks/footer-block/README.md
>  This block does not emit any events.
```suggestion
This block does not emit or listen for events.
```

2022-09-02 20:20 UTC, ecarlisle approved these changes

2022-09-02 20:53 UTC, nschubach commented on blocks/footer-block/_index.scss
> +		> *:first-child {
```suggestion

		> *:first-child {
```

2022-09-06 08:16 UTC, matthewroach commented on blocks/footer-block/_index.scss
> +			@include scss.block-properties("footer-social-links-first");
I see we are setting styles for last child but not first child. Is this for future proofing?

2022-09-06 08:17 UTC, matthewroach approved these changes

2022-09-06 14:39 UTC, nschubach commented on blocks/footer-block/_index.scss
> +			@include scss.block-properties("footer-social-links-first");
Yeah, I debated on whether I brought back the `not-last` token or exposing the first and last for styling.  I thought this was more flexible.

2022-09-07 16:29 UTC, merged