THEMES-751 - Add divider block
WPMedia/fusion-news-theme-blocks pull request #1578
Opened 2022-12-16 14:45 UTC by matthewroach

## Description

Added a new block "Divider Block"

## Jira Ticket

- [THEMES-751](https://arcpublishing.atlassian.net/browse/THEMES-751)

## Test Steps

Requires feature pack PR

1. Checkout this branch `git checkout THEMES-751`
2. Checkout the feature pack branch `THEMES-751`
3. Add `@local` to the divider block in the blocks.json blocks array `@wpmedia/divider-block@local`
4. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/divider-block`
5. On an existing page at the divider block to the main section of the right rail layout and place between two blocks
6. Verify a dividing line is output between the two blocks

## Dependencies or Side Effects

Feature Pack PR - 
Manifest PR - 

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2022-12-16 19:04 UTC, nschubach requested changes, later dismissed
Minor change

2022-12-16 19:04 UTC, nschubach commented on blocks/divider-block/package.json
> +    "@arc-fusion/prop-types": "^0.1.5",
```suggestion
```
I don't see this dependency

2022-12-19 10:00 UTC, matthewroach commented on blocks/divider-block/package.json
> +    "@arc-fusion/prop-types": "^0.1.5",
Fixed

2022-12-19 14:40 UTC, rmbrntt approved these changes

2022-12-19 14:43 UTC, merged