THEMES-1086: Move resizer URL
WPMedia/fusion-news-theme-blocks pull request #1654
Opened 2023-04-19 19:02 UTC by vgalatro

## Description

This PR updates the resizer URL so it comes from site properties instead of an environment variable. This is to prevent customers needing to change where this is set when upgrading to 2.0.

## Jira Ticket

- [THEMES-1086](https://arcpublishing.atlassian.net/browse/THEMES-1086)

## Acceptance Criteria

The resizer url is a site property in Themes Settings, not an env variable

## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout THEMES-1086`
2. Checkout the same branch for `arc-themes-components` and `arc-themes-feature-pack` 
3. Run fusion repo with linked blocks `npx fusion start -f -l`
4. On the all blocks test page, verify that images are still loading, and using the resizer URL.

## Dependencies or Side Effects

- Themes Components PR: https://github.com/WPMedia/arc-themes-components/pull/179
  - After this PR is merged, this branch will need to be updated with new `arc-themes-components` version in the `package-lock.json` for Chromatic tests to pass.
- Feature Pack PR: https://github.com/WPMedia/arc-themes-feature-pack/pull/401

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [x] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1086]: https://arcpublishing.atlassian.net/browse/THEMES-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-20 14:28 UTC, blakeganderson submitted a review, later dismissed
LGTM! just needs the latest 2.0.3 changes merged in

2023-04-21 20:13 UTC, vgalatro commented
Moving this back to WIP since there's so many issues with tests happening.

2023-04-21 21:09 UTC, neilsmind commented on package-lock.json
[Question] Why did the package-lock.json file get regenerated / create so much churn in the PR?

2023-04-25 11:29 UTC, rmbrntt commented on package-lock.json
Anyone running `npm i` should be on node 14, most are using nvm to manage node versions as some repos are on different node versions. If someone ran `npm i` on another node version it will re-generate a package-lock.json.

2023-04-26 14:48 UTC, nschubach commented
I don't want to lose these story files in the git history... I might be fine with renaming them for now so they are not picked up or something.  If they are failing we could also potentially accept them as failures for now?

2023-04-26 14:54 UTC, nschubach commented on package-lock.json
For a little more history... Chromatic uses the package-lock file as it's source of truth for the revision of packages that it uses (which makes sense, it should match the package lock that the dev checked in...)  We've noticed that when changes are made in supporting repos and `npm i` is not run locally before pushing it causes Chromatic to pull the old modules.  It works for the developer because they are linking to our local files when running so they don't notice it in the storybook and the push proceeds fine.  When it gets to github and chromatic goes to grab those packages, it's getting outdated code and can fail.

At least, that's one scenario that I've witnessed.  Short of requiring that all developers run `npm i` religiously, I don't know of a "simple" fix for this.

2023-04-26 15:13 UTC, nschubach requested changes
I'd like to retain these deleted files in some way.  Either through opening a new PR to re-add them at some point, renaming them, or just marking the broken results as "acceptable" for now since we know this has an impact on those when included in 2.0.x

2023-04-26 17:12 UTC, vgalatro commented
@nschubach , I've renamed the stories as `story-ignore` to keep the files in the repo.

2023-04-26 18:10 UTC, nschubach approved these changes

2023-04-26 18:11 UTC, merged