THEMES-1079 Update the subheadline font to 20px level 6
WPMedia/fusion-news-theme-blocks pull request #1662
Opened 2023-05-09 13:56 UTC by alvajardila

## Description

- V2 Subheadline | Arc Block - Update the subheadline font to 20px level 6 instead of level 3

![image](https://user-images.githubusercontent.com/2062473/236938869-7e3f8e08-ab23-4595-951a-b367f3302961.png)

## Jira Ticket

- [THEMES-1079](https://arcpublishing.atlassian.net/browse/THEMES-1079)

## Acceptance Criteria

_copy from ticket_

## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l {blocks to link}`
3. {Next ....}

## Effect Of Changes

### Before

_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After

_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects

_Examples of dependencies or side effects are:_

- Manifest pr for new block:
- Feature pack pr for local development:
- How to deploy to news: https://arcpublishing.atlassian.net/wiki/spaces/TI/pages/3138682964/News+Theme+2.0+Migration+Development+Deployment+Notes
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Dependency on another PR that needs to be merged first

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2023-05-11 15:17 UTC, nschubach commented
@malavikakoppula : was there a specific reason you marked this "do not merge" previously?

2023-05-11 15:30 UTC, malavikakoppula commented
> @malavikakoppula : was there a specific reason you marked this "do not merge" previously?

For some reason, Styles are still not matching to the heading-level-6 designs.

2023-05-15 19:16 UTC, malavikakoppula requested changes
For font-size, font-weight and line-height have to refer to heading-level-6

2023-05-15 19:16 UTC, malavikakoppula commented on .storybook/themes/news.scss
> +					font-size: var(--heading-level-5-font-size),
change this to `font-size: var(--heading-level-6-font-size)`

2023-05-15 19:16 UTC, malavikakoppula commented on .storybook/themes/news.scss
> +					font-weight: var(--heading-level-7-font-weight),
`heading-level-7-font-weight` on `font-weight ` is not existed. Change to `heading-level-6-font-weight`

2023-05-15 19:16 UTC, malavikakoppula commented on .storybook/themes/news.scss
> +					line-height: var(--heading-level-5-line-height),
same as above, change to `heading-level-6-line-height`

2023-05-15 19:16 UTC, malavikakoppula commented on blocks/subheadline-block/themes/news.json
> +				"line-height": "var(--heading-level-5-line-height)"
"font-size": "var(--heading-level-6-font-size)",
"font-weight": "var(--heading-level-6-font-weight)",
"line-height": "var(--heading-level-6-line-height)"

2023-05-18 20:42 UTC, malavikakoppula approved these changes
LGTM

2023-05-26 17:52 UTC, pardistaherzadeh commented
@alvajardila It is approved and ready to be merged.

2023-05-31 15:37 UTC, merged