Lead Art Gallery + Article Body Gallery | Disable smart crop
WPMedia/fusion-news-theme-blocks pull request #1677
Opened 2023-06-09 22:50 UTC by GioLopWP

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
This PR set to false the smart crop for the carousel image for LeadArt block.

_Information about what you changed for this PR_

## Jira Ticket

- [THEMES-1034](https://arcpublishing.atlassian.net/browse/THEMES-1034)

## Acceptance Criteria

GIVEN I am an Editor, WHEN a gallery is the lead art on in the article body on an article, THEN: 

Smart crop is false for the images on the gallery lead art and the article body galleries

Full images display in the gallery view

## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout THEMES-1034`
2. Run fusion repo with linked blocks `npx fusion start -f -l lead-art-block`
3. In composer create a new story with carousel
4. Use page builder to use the lead-art-block in a page bringing the story that was created
5. Safe and Publish
6. Go to the page preview

## Effect Of Changes
Images should display a black frame without resizing or cutting the content

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2023-06-13 18:52 UTC, nschubach requested changes

2023-06-13 18:52 UTC, nschubach commented on blocks/lead-art-block/features/leadart/default.jsx
> +										resizedOptions={{ smart: false }}
I think this would work if you just remove this line... not passing in smart would not define it so it would not be true.

2023-06-13 19:19 UTC, nschubach commented on blocks/lead-art-block/features/leadart/default.jsx
> +										resizedOptions={{ smart: false }}
```suggestion
```

2023-06-13 21:35 UTC, GioLopWP commented on blocks/lead-art-block/features/leadart/default.jsx
> +										resizedOptions={{ smart: false }}
@nschubach, Hi Nick thank you for reviewing this, change is done.

2023-06-14 15:13 UTC, nschubach approved these changes

2023-06-14 16:27 UTC, pardistaherzadeh commented
It is approved and ready to merge.

2023-06-14 16:29 UTC, merged