PEN-415 Alert Bar
WPMedia/fusion-news-theme-blocks pull request #169
Opened 2020-03-19 14:42 UTC by shk172

[JIRA](https://arcpublishing.atlassian.net/browse/PEN-415)

Note: This includes the preliminary content source for alert bar just so it can be tested properly in prod. Once https://arcpublishing.atlassian.net/browse/PEN-570 is unblocked it will be updated

2020-03-20 18:13 UTC, JackHowa reviewed
Oh, this is a draft. my review is probably not quite needed yet ...

2020-03-25 16:55 UTC, jgrosspietsch requested changes

2020-04-10 14:45 UTC, JackHowa reviewed
A few minor nits -- otherwise, will approve

2020-04-10 15:35 UTC, JackHowa approved these changes

2020-04-10 15:37 UTC, jgrosspietsch approved these changes
Pretty much everything has been addressed.

2020-04-10 15:54 UTC, merged