Themes 1088
WPMedia/fusion-news-theme-blocks pull request #1721
Opened 2023-08-16 16:29 UTC by malavikakoppula

## Description

The underlying engine-theme-sdk doesn’t allow eager loading of images. We’d need to make updates to enable passing eager down through the tree of children gallery (block) > gallery (sdk) > image (sdk). 

## Jira Ticket

- [THEMES-1088](https://arcpublishing.atlassian.net/browse/THEMES-1088)

## Acceptance Criteria

Eager loading policy can be applied on the gallery lead art block and gallery block so they can specify which image(s) eager load

Note: the rest default to lazy
## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout THEMES-1088
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/lead-art-block,@wpmedia/gallery-block`
3. Image load as eager

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1088]: https://arcpublishing.atlassian.net/browse/THEMES-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-22 17:42 UTC, vgalatro requested changes
It'll be slight, but we can make the page load a bit faster if we only eager load the first image in a gallery. The other images should always be `lazy` loaded since they won't immediately be in view. So something like `loading={(itemIndex === 0) ? "eager" : "lazy"}`, and still use `imageLoadingStrategy` instead of `eager` in the lead art block.

2023-08-24 14:15 UTC, malavikakoppula commented
> d2f9c13

@vgalatro Hope I understood your suggestions... here are my changes https://github.com/WPMedia/arc-themes-blocks/pull/1721/commits/d2f9c13ce339ebdddf516545d0702c90d7d690f6

2023-08-25 13:25 UTC, vgalatro commented
@malavikakoppula , yes that's the change needed. It should also be on the lead art block. We want to make sure the images other than first are lazy loaded since they'll never be in view on page load. It would just be a bit different since there's the `imageLoadingStrategy` custom field. So we should use that value for the first image instead of hard coding it to `eager`.

2023-08-28 14:00 UTC, malavikakoppula commented
> fefc5e5

@vgalatro Fixed this https://github.com/WPMedia/arc-themes-blocks/pull/1721/commits/fefc5e5eb7916d39e7a94dad823094d985d5b2aa

2023-08-28 14:09 UTC, vgalatro approved these changes
LGTM! Thanks for making those changes.

2023-08-28 14:33 UTC, merged