[Themes 1211] Logical properties on manual-promo blocks
WPMedia/fusion-news-theme-blocks pull request #1834
Opened 2023-12-06 14:53 UTC by malavikakoppula

## Description

Update padding, margin, and border properties. The following conversions must be done:

1. *-top and *-bottom need to be changed to *-block.
2. *-left and *-right need to be changed to *-inline.
3. height and width will need to be set to block-size and inline-size respectively

## Jira Ticket

- [THEMES-1211](https://arcpublishing.atlassian.net/browse/THEMES-1211)

## Acceptance Criteria

1. The above logical properties are applied and tested on the manual promo blocks.
2. Storybook is updated with RTL.

## Test Steps

1. Checkout this branch `git checkout THEMES-1211`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/extra-large-manual-promo-block,@wpmedia/large-manual-promo-block,@wpmedia/medium-manual-promo-block,@wpmedia/small-manual-promo-block`
3. Set "textDirection": "rtl" in the "siteProperties" object of the blocks.json
4. content source _id: PKFVHJKBBVHZRIHJEMQGGREWIE
5. Check the styles for RTL matching to Figma designs

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1211]: https://arcpublishing.atlassian.net/browse/THEMES-1211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-07 21:05 UTC, vgalatro requested changes
There's a couple of changes that need to be reverted and also a question on a change in a test file.

2023-12-07 21:05 UTC, vgalatro commented on blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
> +					{["inset-block-end", "inset-inline-end"].includes(imagePosition) ? (
This change will cause two problems. First, neither of these are in the list of allowed options for the custom field. Second, it would break current configurations of this block as PB editor would have `below` and `right` stored in the DB. The UI should stay the way it is for now, we only need to update the related values in the themes JSON.

2023-12-07 21:05 UTC, vgalatro commented on blocks/small-manual-promo-block/features/small-manual-promo/default.test.jsx
> +		expect(screen.getByRole("img", { hidden: true })).not.toBeNull();
Is there a reason this change was made?

2023-12-07 21:05 UTC, vgalatro commented on blocks/small-promo-block/features/small-promo/default.jsx
> +					{["inset-block-end", "inset-inline-end"].includes(imagePosition) ? (
Same as in the small manual promo block, this should not be changed right now.

2023-12-07 21:10 UTC, malavikakoppula commented on blocks/small-manual-promo-block/features/small-manual-promo/default.test.jsx
> +		expect(screen.getByRole("img", { hidden: true })).not.toBeNull();
Yes, Due to Github warnings I have changed this

2023-12-11 14:56 UTC, malavikakoppula commented on blocks/small-promo-block/features/small-promo/default.jsx
> +					{["inset-block-end", "inset-inline-end"].includes(imagePosition) ? (
@vgalatro Reverted this change [d2e6fcf](https://github.com/WPMedia/arc-themes-blocks/pull/1834/commits/d2e6fcfb1200383a19f07142b1f6b5854bdd35e9)

2023-12-11 14:56 UTC, malavikakoppula commented on blocks/small-manual-promo-block/features/small-manual-promo/default.jsx
> +					{["inset-block-end", "inset-inline-end"].includes(imagePosition) ? (
@vgalatro Reverted this change [d2e6fcf](https://github.com/WPMedia/arc-themes-blocks/pull/1834/commits/d2e6fcfb1200383a19f07142b1f6b5854bdd35e9)

2023-12-11 15:30 UTC, vgalatro approved these changes
LGTM!

2023-12-11 16:37 UTC, merged