ASUB-8484 Including threshold for pending order and fixing styles
WPMedia/fusion-news-theme-blocks pull request #2133
Opened 2024-05-17 13:59 UTC by LauraPinilla

**Be sure to run `npm test`, `npm run lint`, and write detailed test steps before requesting reviewers**

## Description

#### Jira Ticket: [THEMES-](https://arcpublishing.atlassian.net/browse/THEMES-)
https://arcpublishing.atlassian.net/browse/ASUB-8484

_Information about what you changed for this PR. Include any dependencies, companion PRs, relevant screenshots, or config changes._

## Test Steps

_Add detailed test steps a reviewer must complete to test this PR_

1. Checkout this branch `git checkout {branch name}`
2. Run fusion repo with linked blocks `npx fusion start -f -l {blocks to link}`
3. {Next ....}

2024-05-24 18:44 UTC, vgalatro requested changes
I have some questions about the styling changes. Adding styles directly to the `_index.scss` files is something we try to avoid as much as possible. It leads to conflicts and makes is so clients can't override them, negating the primary advantage of Themes v2 block styling.

2024-05-24 18:44 UTC, vgalatro commented on blocks/subscriptions-block/_index.scss
> +}
Why is this being done here instead of in the `checkout-main` and `checkout-sidebar` tokens in the `news.json`? And why at a breakpoint different than the Themes default one?

2024-05-24 20:44 UTC, LauraPinilla commented on blocks/subscriptions-block/_index.scss
> +}
Hi @vgalatro, I can't remember what kind of code I tried in the past using default & desktop, but now It works for me. Thanks.

2024-05-28 17:43 UTC, vgalatro approved these changes
LGTM!

2024-05-30 13:30 UTC, vgalatro commented
@LauraPinilla , this is good to merge in, we were planning on launching 2.4.0 to sandbox today.

2024-05-30 14:17 UTC, merged