PEN-1604 Google Ad Block | Out of Page: False for oop adtype
WPMedia/fusion-news-theme-blocks pull request #657
Opened 2021-01-06 08:58 UTC by ktran-wizeline

**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
_Information about what you changed for this PR_

The OOP ad is displaying as Out of Page: False in the googleconsole and therefore no ad would render. Will Cook looked into this and determined the following update needs to be made for the oop ad. 

Following this documentation, https://github.com/washingtonpost/arcads#out-of-page-ads
_If an advertisement has an empty or missing dimensions parameter it will be considered as a DFP Out of Page creative and rendered as such._

## Jira Ticket
- [PEN-1604](https://arcpublishing.atlassian.net/browse/PEN-1604)

## Acceptance Criteria
_copy from ticket_
Google ad - OOP should work

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. In Fusion-News-Theme repo, checkout master & git pull
2. After checking out this feature branch in fusion-news-theme-blocks, run `rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..`
3. Run: `npx fusion start -f -l @wpmedia/ads-block`
4. Create a page then add the google ad block, configure ad type as OOP for testing.

## Effect Of Changes
### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working. 
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist 
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr. 
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-01-06 08:59 UTC, ktran-wizeline commented
Sorry but I don't know how to test this story on my local dev env, I did not see any effect when using google ad block with OOP ad type.

2021-01-06 11:40 UTC, JackHowa commented
would recommend talking with @vinnie-olsen for testing ad blocks. there's also probably some documentation in previous prs with the ads block

2021-01-06 11:41 UTC, JackHowa requested changes
No test instructions included. Sorry, Khoa, not sure if this is ready for review yet

2021-01-06 16:09 UTC, ktran-wizeline commented
> No test instructions included. Sorry, Khoa, not sure if this is ready for review yet

@JackHowa  I updated the test steps and screenshot on my dev env. Thank @vinnie-olsen for your instruction to verify this story!

2021-01-07 12:31 UTC, JackHowa commented
@ktran-wizeline , reviewing now -- sorry

2021-01-07 12:44 UTC, JackHowa commented
<img width="1388" alt="Screen Shot 2021-01-07 at 12 44 22" src="https://user-images.githubusercontent.com/5950956/103893976-14681e00-50e6-11eb-83e5-93204fd16719.png">
seeing this warning, have you seen this? 


```
react.development.js?72d0:167 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in FusionQuarantine(ArcAd)
    in Unknown (created by Context.Consumer)
    in Unknown (created by BanditoWrapper)
    in BanditoWrapper

2021-01-07 12:48 UTC, JackHowa commented
<img width="501" alt="Screen Shot 2021-01-07 at 12 48 18" src="https://user-images.githubusercontent.com/5950956/103894297-a2440900-50e6-11eb-8ff7-c96b8154708e.png">

seeing issue with googleTag? expected?

2021-01-07 12:52 UTC, JackHowa commented
@ktran-wizeline was able to verify by going to actual published page. in the future, please include that in the instructions for how to verify. reviewers should not need to know anything outside of your instructions 

<img width="1056" alt="Screen Shot 2021-01-07 at 12 51 01" src="https://user-images.githubusercontent.com/5950956/103894645-23030500-50e7-11eb-84b3-c98f4f17452e.png">

2021-01-07 13:06 UTC, JackHowa approved these changes
achieves the goal of the ticket. not sure of potential side effects

2021-01-07 14:17 UTC, merged