Simple results list
WPMedia/fusion-news-theme-blocks pull request #70
Opened 2020-01-02 16:41 UTC by RohitTWP

2020-01-03 16:44 UTC, jgrosspietsch requested changes

2020-01-13 16:21 UTC, beltrancaliz approved these changes

2020-01-13 19:33 UTC, beltrancaliz approved these changes

2020-01-15 18:19 UTC, brentmiller1973 reviewed
Looks good, but images coming from the content source needs to leverage the Image component in the engine-sdk so that it can get resized.

2020-01-28 14:30 UTC, merged