Tmedia 84 remove unnecessary deps
WPMedia/fusion-news-theme-blocks pull request #886
Opened 2021-05-25 16:14 UTC by JackHowa

## Description
Remove one unnecessary top-level dep. Change tag matching `stable` and `canary` tags to any `*`. This will help with npm 7 migration which will result in smaller bundles

## Jira Ticket
- [TMEDIA-84](https://arcpublishing.atlassian.net/secure/RapidBoard.jspa?rapidView=875&modal=detail&selectedIssue=TMEDIA-84&assignee=5e387d6a1b1d910e5dfd7a9b)

## Acceptance Criteria
- Remove unnecessary deps
- Improve bundle size eventually

## Test Steps

1. Checkout this branch `git checkout TMEDIA-84-remove-unnecessary-deps`
2. Run fusion repo with linked blocks `rm -rf node_modules && npm i && npm t`
3. Ensure tests run as before

## Effect Of Changes
### Before
- Targeting wrong tags with peer deps and npm@7 warnings

### After
- Fewer warnings and unnecessary deps 

## Dependencies or Side Effects
- No side effects 

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

2021-05-25 16:15 UTC, JackHowa commented on package.json
> +    "@wpmedia/video-promo-block": "file:blocks/video-promo-block"
removed focus trap from top-level dep, not sure why it was there. Has duplicate value in the block

2021-05-25 18:20 UTC, matthewroach approved these changes

2021-05-25 18:21 UTC, matthewroach requested changes
You need to commit package-lock.json changes when making package.json updates

2021-05-26 14:52 UTC, JackHowa commented
@matthewroach updated, my bad. I'd gotten into the habit of not updating blocks' package-locks

2021-05-26 15:59 UTC, matthewroach approved these changes

2021-05-26 16:02 UTC, merged